"""Table update

Revision ID: 43873ac7c030
Revises: 
Create Date: 2022-02-11 13:05:53.428622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43873ac7c030'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=25), nullable=False),
    sa.Column('city', sa.String(length=25), nullable=False),
    sa.Column('address', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental_point'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=40), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacture', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('classifications', sa.String(length=15), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('number_plate', sa.String(length=10), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=False),
    sa.Column('rental_point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rental_point_id'], ['rental_point.id'], name=op.f('fk_car_rental_point_id_rental_point')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_car'))
    )
    op.create_table('user_car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.String(length=20), nullable=False),
    sa.Column('to_date', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('reservation_number', sa.Integer(), nullable=True),
    sa.Column('booked_status', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], name=op.f('fk_user_car_car_id_car')),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_user_car_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_car'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_car')
    op.drop_table('car')
    op.drop_table('user')
    op.drop_table('rental_point')
    # ### end Alembic commands ###
