"""Pievienots Country

Revision ID: 48c702ae7fe1
Revises: 
Create Date: 2022-01-31 21:53:34.057619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c702ae7fe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=48), nullable=False),
    sa.Column('abbreviation', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    # ### end Alembic commands ###
