"""Car papildinajums

Revision ID: 7e4c852ac448
Revises: 43873ac7c030
Create Date: 2022-02-18 16:16:41.140480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4c852ac448'
down_revision = '43873ac7c030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('from_date', sa.String(length=20), nullable=False))
    op.add_column('car', sa.Column('to_date', sa.String(length=20), nullable=False))
    op.alter_column('user_car', 'reservation_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_car', 'reservation_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('car', 'to_date')
    op.drop_column('car', 'from_date')
    # ### end Alembic commands ###
