"""Nomainīts valstu datu tipu veids

Revision ID: b0768990294d
Revises: 48c702ae7fe1
Create Date: 2022-02-01 20:21:35.753825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0768990294d'
down_revision = '48c702ae7fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('number', sa.String(length=18), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agency'))
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=48), nullable=False),
    sa.Column('abbreviation', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country'))
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('country_from', sa.Integer(), nullable=True),
    sa.Column('country_to', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=280), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('ticket_amount', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name=op.f('fk_trip_agency_id_agency')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    op.drop_table('country')
    op.drop_table('agency')
    # ### end Alembic commands ###
